# Generated by Django 5.2.9 on 2026-01-12 08:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CenterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('center_variety', models.CharField(blank=True, choices=[('EXAM', 'Exam Center'), ('MARKFED', 'Markfed '), ('DEMO', 'Demo')], max_length=50, null=True)),
                ('center_type', models.CharField(blank=True, choices=[('SCHOOL', 'School'), ('COLLEGE', 'College'), ('UNIVERSITY', 'University'), ('WORKSHOP', 'Workshop'), ('PRIVATE_LAB', 'Private Lab'), ('COACHING', 'Coaching'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('ownership_type', models.CharField(blank=True, choices=[('GOVT', 'Government'), ('PRIVATE', 'Private'), ('AIDED', 'Aided'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('geofence_radius_meters', models.IntegerField(default=200)),
                ('total_rooms', models.IntegerField(blank=True, null=True)),
                ('total_labs', models.IntegerField(blank=True, null=True)),
                ('max_candidates_overall', models.IntegerField(blank=True, null=True)),
                ('max_computers', models.IntegerField(blank=True, null=True)),
                ('buffer_candidates_count', models.IntegerField(default=0)),
                ('internet_speed_mbps', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('has_generator_backup', models.BooleanField(default=False)),
                ('total_computers_functional', models.IntegerField(blank=True, null=True)),
                ('incharge_name', models.CharField(blank=True, max_length=150, null=True)),
                ('incharge_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('incharge_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alt_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('alt_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLISTED', 'Blacklisted'), ('UNDER_REVIEW', 'Under Review')], default='ACTIVE', max_length=30)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_exams_conducted', models.IntegerField(default=0)),
                ('last_exam_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'center_master',
                'indexes': [models.Index(fields=['center_code'], name='center_mast_center__ce5bf0_idx'), models.Index(fields=['city', 'state'], name='center_mast_city_0fc50e_idx'), models.Index(fields=['status'], name='center_mast_status_ab2392_idx'), models.Index(fields=['latitude', 'longitude'], name='center_mast_latitud_a6ea62_idx')],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('primary_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('secondary_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('secondary_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PROSPECT', 'Prospect')], default='ACTIVE', max_length=20)),
                ('exam_count', models.IntegerField(default=0)),
                ('exam_active_count', models.IntegerField(default=0)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'client',
                'indexes': [models.Index(fields=['client_code'], name='client_client__07b5d9_idx'), models.Index(fields=['status'], name='client_status_5321f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('instruction', models.TextField(blank=True, null=True)),
                ('training_video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('requires_training_completion', models.BooleanField(default=False)),
                ('dress_code', models.CharField(blank=True, max_length=255, null=True)),
                ('age_min', models.IntegerField(blank=True, null=True)),
                ('age_max', models.IntegerField(blank=True, null=True)),
                ('gender_requirement', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('tag_color', models.CharField(blank=True, max_length=50, null=True)),
                ('default_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'role',
                'indexes': [models.Index(fields=['code'], name='role_code_df16be_idx'), models.Index(fields=['is_active'], name='role_is_acti_d578e4_idx')],
            },
        ),
    ]
