# Generated by Django 5.2.9 on 2026-01-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemaster',
            options={'ordering': ['name']},
        ),
    ]
