# Generated by Django 5.2.9 on 2026-02-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_rolemaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='admin_password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='admin_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
