# Generated by Django 5.2.9 on 2026-02-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_client_admin_password_client_admin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centermaster',
            name='center_type',
        ),
        migrations.AddField(
            model_name='centermaster',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centers', to='masters.client'),
        ),
    ]
