# Generated by Django 5.2.9 on 2026-02-06 05:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_remove_centermaster_center_type_centermaster_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Task Library',
                'ordering': ['name'],
            },
        ),
    ]
