# Generated by Django 5.2.9 on 2026-02-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_tasklibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklibrary',
            name='task_type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('PHOTO', 'Photo'), ('VIDEO', 'Video')], default='CHECKLIST', max_length=20),
        ),
    ]
