# Generated by Django 4.2.27 on 2025-12-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('current_state', models.CharField(blank=True, max_length=100, null=True)),
                ('current_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('current_district', models.CharField(blank=True, max_length=100, null=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_state', models.CharField(blank=True, max_length=100, null=True)),
                ('permanent_zip', models.CharField(blank=True, max_length=20, null=True)),
                ('permanent_district', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PROFILE_FILLED', 'Profile Filled'), ('KYC_IN_PROGRESS', 'KYC In Progress'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20)),
                ('verification_method', models.CharField(choices=[('NONE', 'None'), ('AADHAAR', 'Aadhaar'), ('DL', 'Driving Licence')], default='NONE', max_length=10)),
                ('kyc_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('FACE_PENDING', 'Face Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_fail_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['profile_status'], name='operators_o_profile_4ff985_idx'), models.Index(fields=['kyc_status'], name='operators_o_kyc_sta_5f0c73_idx')],
            },
        ),
    ]
