# Generated by Django 5.2.9 on 2025-12-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
