# Generated by Django 5.2.9 on 2026-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpsession_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
