# Generated by Django 5.2.9 on 2026-02-02 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appuser_photo'),
        ('masters', '0002_alter_rolemaster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='masters.client'),
        ),
    ]
