# Generated by Django 5.2.9 on 2026-02-03 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_appuser_client'),
        ('operations', '0002_alter_shiftcenter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='operations.exam'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_type',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('CLIENT_ADMIN', 'Client Admin'), ('CLIENT_VIEWER', 'Client Viewer'), ('INTERNAL_ADMIN', 'Internal Admin'), ('EXAM_ADMIN', 'Exam Admin')], default='OPERATOR', max_length=30),
        ),
    ]
