# Generated by Django 5.2.9 on 2026-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appuser_exam_alter_appuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='mobile_primary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='otpsession',
            name='mobile',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
