# Generated by Django 5.2.9 on 2026-01-12 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary'), ('BUFFER', 'Buffer/Standby')], default='PRIMARY', max_length=20)),
                ('payout_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(limit_choices_to={'user_type': 'OPERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='masters.rolemaster')),
                ('shift_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.shiftcenter')),
            ],
            options={
                'db_table': 'operator_assignment',
                'indexes': [models.Index(fields=['operator', 'status'], name='operator_as_operato_10e51e_idx'), models.Index(fields=['shift_center'], name='operator_as_shift_c_8ec574_idx'), models.Index(fields=['status', 'assigned_at'], name='operator_as_status_83de25_idx')],
            },
        ),
    ]
