# Generated by Django 5.2.9 on 2026-01-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatorassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterField(
            model_name='operatorassignment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CHECK_IN', 'Checked In'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
