# Generated by Django 5.2.9 on 2026-02-06 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_operatorassignment_options_and_more'),
        ('operations', '0004_shiftcentertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='assignments.operatorassignment')),
                ('shift_center_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_tasks', to='operations.shiftcentertask')),
            ],
            options={
                'db_table': 'assignment_task',
                'unique_together': {('assignment', 'shift_center_task')},
            },
        ),
    ]
