# Generated by Django 5.2.9 on 2026-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignmenttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_evidence/'),
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='response_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
