# Generated by Django 5.2.9 on 2026-01-12 09:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exam_type', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_start_date', models.DateField(blank=True, null=True)),
                ('exam_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIGURING', 'Configuring'), ('READY', 'Ready'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('attachments_url', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exams', to='masters.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_center_code', models.CharField(db_index=True, max_length=50)),
                ('client_center_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('geofence_radius_meters', models.IntegerField(default=200)),
                ('active_capacity', models.IntegerField(blank=True, null=True)),
                ('expected_candidates', models.IntegerField(default=0)),
                ('incharge_name', models.CharField(blank=True, max_length=150, null=True)),
                ('incharge_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('lab_room_info', models.CharField(blank=True, max_length=255, null=True)),
                ('client_specific_instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_centers', to='operations.exam')),
                ('master_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_centers', to='masters.centermaster')),
            ],
            options={
                'db_table': 'exam_center',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shift_code', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('session_number', models.IntegerField(blank=True, null=True)),
                ('work_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('gate_close_time', models.TimeField(blank=True, null=True)),
                ('exam_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('MOCK', 'Mock'), ('MAIN', 'Main')], default='MAIN', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIGURING', 'Configuring'), ('READY', 'Ready'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_created', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='operations.exam')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shift',
            },
        ),
        migrations.CreateModel(
            name='ShiftCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_centers', to='operations.exam')),
                ('exam_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_centers', to='operations.examcenter')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_centers', to='operations.shift')),
            ],
            options={
                'db_table': 'shift_center',
            },
        ),
        migrations.CreateModel(
            name='ShiftCenterRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headcount', models.IntegerField()),
                ('buffer_headcount', models.IntegerField(default=0)),
                ('male_count', models.IntegerField(blank=True, null=True)),
                ('female_count', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_center_assignments', to='masters.rolemaster')),
                ('shift_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='operations.shiftcenter')),
            ],
            options={
                'db_table': 'shift_center_role',
            },
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_code'], name='exam_exam_co_859968_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['client'], name='exam_client__e4edf1_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['status'], name='exam_status_f30347_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_start_date', 'exam_end_date'], name='exam_exam_st_60d2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='examcenter',
            index=models.Index(fields=['exam'], name='exam_center_exam_id_d0cfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='examcenter',
            index=models.Index(fields=['master_center'], name='exam_center_master__cdeb52_idx'),
        ),
        migrations.AddIndex(
            model_name='examcenter',
            index=models.Index(fields=['client_center_code'], name='exam_center_client__15fb11_idx'),
        ),
        migrations.AddIndex(
            model_name='examcenter',
            index=models.Index(fields=['status'], name='exam_center_status_7a056b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examcenter',
            unique_together={('exam', 'client_center_code')},
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['exam', 'work_date'], name='shift_exam_id_bf24c9_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status'], name='shift_status_ff6034_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('exam', 'shift_code')},
        ),
        migrations.AddIndex(
            model_name='shiftcenter',
            index=models.Index(fields=['shift', 'exam_center'], name='shift_cente_shift_i_f9970b_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftcenter',
            index=models.Index(fields=['status'], name='shift_cente_status_35447f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftcenter',
            unique_together={('exam', 'shift', 'exam_center')},
        ),
        migrations.AddIndex(
            model_name='shiftcenterrole',
            index=models.Index(fields=['shift_center', 'role'], name='shift_cente_shift_c_bb55b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftcenterrole',
            unique_together={('shift_center', 'role')},
        ),
    ]
