# Generated by Django 5.2.9 on 2026-02-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_shiftcenter_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='admin_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='admin_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
