# Generated by Django 5.2.9 on 2026-02-06 05:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0005_tasklibrary'),
        ('operations', '0003_exam_admin_password_exam_admin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftCenterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_name', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_tasks', to='masters.rolemaster')),
                ('shift_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.shiftcenter')),
            ],
            options={
                'db_table': 'shift_center_task',
                'indexes': [models.Index(fields=['shift_center', 'role'], name='shift_cente_shift_c_32c80c_idx')],
                'unique_together': {('shift_center', 'role', 'task_name')},
            },
        ),
    ]
