# Generated by Django 5.2.9 on 2026-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_shiftcentertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_geofencing_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
