# Generated by Django 5.2.9 on 2026-02-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_exam_is_geofencing_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_selfie_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
