# Generated by Django 5.2.9 on 2026-02-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_exam_is_selfie_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcentertask',
            name='task_type',
            field=models.CharField(choices=[('CHECKLIST', 'Checklist'), ('PHOTO', 'Photo'), ('VIDEO', 'Video')], default='CHECKLIST', max_length=20),
        ),
    ]
