# Generated by Django 5.2.9 on 2026-02-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_shiftcentertask_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
