# Generated by Django 5.2.9 on 2026-02-13 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_examcenter_city'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together={('exam', 'shift_code', 'work_date')},
        ),
    ]
