# Generated by Django 6.0.2 on 2026-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_alter_shift_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcenter',
            name='operators_required',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
