# Generated by Django 6.0.2 on 2026-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_examcenter_operators_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftcenter',
            name='operators_required',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
