# Generated by Django 4.2.27 on 2025-12-26 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kyc.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('DL', 'Driving Licence')], max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('name_match', models.BooleanField(blank=True, null=True)),
                ('name_match_score', models.FloatField(blank=True, null=True)),
                ('dob_match', models.BooleanField(blank=True, null=True)),
                ('gender_match', models.BooleanField(blank=True, null=True)),
                ('liveness_pass', models.BooleanField(blank=True, null=True)),
                ('liveness_confidence', models.FloatField(blank=True, null=True)),
                ('face_match_pass', models.BooleanField(blank=True, null=True)),
                ('face_match_confidence', models.FloatField(blank=True, null=True)),
                ('dedupe_hash', models.CharField(db_index=True, max_length=64)),
                ('vendor_reference_id', models.CharField(blank=True, max_length=120, null=True)),
                ('vendor_uniqueness_id', models.CharField(blank=True, max_length=120, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['method', 'verified'], name='kyc_userver_method_0a230b_idx'), models.Index(fields=['dedupe_hash'], name='kyc_userver_dedupe__cf921b_idx')],
            },
        ),
        migrations.CreateModel(
            name='KycSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('DL', 'Driving Licence')], max_length=10)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20)),
                ('surepass_client_id', models.CharField(blank=True, max_length=220, null=True)),
                ('dedupe_hash', models.CharField(db_index=True, max_length=64)),
                ('otp_attempts', models.IntegerField(default=0)),
                ('liveness_attempts', models.IntegerField(default=0)),
                ('face_attempts', models.IntegerField(default=0)),
                ('ekyc_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ekyc_dob', models.DateField(blank=True, null=True)),
                ('ekyc_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('name_match_score', models.FloatField(blank=True, null=True)),
                ('name_match', models.BooleanField(blank=True, null=True)),
                ('dob_match', models.BooleanField(blank=True, null=True)),
                ('gender_match', models.BooleanField(blank=True, null=True)),
                ('id_card_image_b64', models.TextField(blank=True, null=True)),
                ('vendor_reference_id', models.CharField(blank=True, max_length=120, null=True)),
                ('vendor_uniqueness_id', models.CharField(blank=True, max_length=120, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=kyc.models.default_kyc_expiry)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='kyc_kycsess_user_id_acbe99_idx'), models.Index(fields=['dedupe_hash'], name='kyc_kycsess_dedupe__82223d_idx'), models.Index(fields=['expires_at'], name='kyc_kycsess_expires_a0ed56_idx')],
            },
        ),
    ]
