# Generated by Django 5.2.9 on 2026-01-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycsession',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('OTP_SENT', 'OTP Sent'), ('OTP_VERIFIED', 'OTP Verified'), ('DL_VERIFIED', 'DL Verified'), ('DETAILS_VERIFIED', 'Details Verified'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20),
        ),
    ]
