# Generated by Django 5.2.9 on 2026-02-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_alter_kycsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsession',
            name='ekyc_address_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
