# Generated by Django 5.2.9 on 2026-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
    ]
